import pandas as pd
df = pd.read_csv("dataset/retail_sales_dataset.csv")
df["Date"] = pd.to_datetime(df["Date"],format="%d-%m-%Y")
print(df.head(5))
print("\nDataset Shape:")
print(df.shape)
print("\nColumn Names:")
print(df.columns)
print("\nDataset Information:")
df.info()
print("\nMissing Values:")
print(df.isnull().sum())
print("\nDuplicate Rows:")
print(df.duplicated().sum())
print("\nData Types:")
print(df.dtypes)
print("\nUnique Gender Values:")
print(df["Gender"].unique())
print("\nUnique Product categories:")
print(df["Product Category"].unique())
print("\nAge Range:")
print(df["Age"].min(),"to",df["Age"].max())
print("\nQuantity Range:")
print(df["Quantity"].min(),"to",df["Quantity"].max())
print("\nPrice Range:")
print(df["Price per Unit"].min(),"to",df["Price per Unit"].max()) 
print("\nChecking Total Amount:")
df["Calculated Amount"] = df["Quantity"] * df["Price per Unit"]
print("Incorrect Total Amount :")
print((df["Total Amount"] != df["Calculated Amount"]).sum())
df.drop(columns = ["Calculated Amount"],inplace=True)
df.drop_duplicates(inplace=True)
df.dropna(inplace=True)
df.reset_index(drop=True,inplace=True)

print("\nFinal Dataset Shape:")
print(df.shape)

df.to_csv("cleaned_retail_sales_dataset.csv",index=False)
print("\nCleaned dataset saved successfully!")